[package]
name = "chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

httparse = "1.8.0"
sha1 = "0.10.5"
base64 = "0.21.0"
